#!/bin/sh

csgo_pid=$(pidof csgo_linux64)
if [ -z "$csgo_pid" ]; then
    /bin/echo -e "\e[31mCSGO needs to be open before you can inject...\e[0m"
    exit 1
fi

if [ ! -d ".git" ]; then
    /bin/echo "We have detected that you have downloaded RiccetHook from the GitHub website. This is the WRONG way to download! Please download RiccetHook with the command 'git clone --recursive TODO'"
fi

# pBypass for crash dumps being sent
sudo rm -rf /tmp/dumps # Remove if it's there
sudo mkdir /tmp/dumps # Make it as root
sudo chmod 000 /tmp/dumps # No permissions

if [ ! -f build_id ]; then
    /bin/echo "build ID not found. Please re-build using the ./build script"
    exit
fi

filename=$(cat build_id)

#Credit: Aixxe @ aixxe.net
if grep -q $filename /proc/$csgo_pid/maps; then
    /bin/echo -e "\e[RiccetHook is already injected... Aborting...\e[0m"
    exit
fi
echo "Injecting Build ID: $filename"

#https://www.kernel.org/doc/Documentation/security/Yama.txt
sudo echo "2" | sudo tee /proc/sys/kernel/yama/ptrace_scope # Only allows root to inject code. This is temp until reboot.

sudo cp $filename /$filename

input="$(
sudo gdb -n -q -batch \
  -ex "attach $csgo_pid" \
  -ex "set \$dlopen = (void*(*)(char*, int)) dlopen" \
  -ex "call \$dlopen(\"/$filename\", 1)" \
  -ex "detach" \
  -ex "quit"
)"

sudo rm /$filename

last_line="${input##*$'\n'}"

if [ "$last_line" != "\$1 = (void *) 0x0" ]; then
    /bin/echo -e "\e[32mRiccetHook was successfully injected!\e[0m"
else
    /bin/echo -e "\e[31mInjection failed, make sure you've compiled...\e[0m"
fi
